<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AssemblyName>angular</AssemblyName>
    <PackageId>angular</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="node_modules\**" />
    <EmbeddedResource Remove="node_modules\**" />
    <None Remove="node_modules\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="dist" />
    <None Include="app.config" />
    <None Update="wwwroot\**\*;web.config">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Dockerfile">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="src\app\admin\attendance\" />
    <Folder Include="src\app\admin\leave\" />
    <Folder Include="src\app\admin\roster\" />
    <Folder Include="src\app\admin\shift\" />
    <Folder Include="src\app\admin\report\" />
  </ItemGroup>
</Project>